### ISSUE TITLE
KeyError with owavelengthRange

### ISSUE THREAD

**Issue by Aureliver** [boada/redshiftCode#3]
Hi,
I hope that you will get this message and have time to take a look at it.
I tried to run your code with spDR-023.fit, but I get the following error : 

Spectra to be checked: 
['spDR2-023.fit']
Checking spectrum 1/1 ...
Loading templates ...
Loading object spectrum ...
Traceback (most recent call last):
  File "visualTemplateRedshift5.py", line 1037, in <module>
    app = App(root, objectSpecFileNames, outDir)
  File "visualTemplateRedshift5.py", line 227, in __init__
    self.currentSpecFileIndex])
  File "visualTemplateRedshift5.py", line 835, in loadObjectSpectrum
    owavelengthRange=oimg[1].data.field('LAMBDA')
  File "/pyfits/fitsrec.py", line 684, in field
    column = self.columns[key]
  File "/pyfits/column.py", line 1463, in __getitem__
    key = _get_index(self.names, key)
  File "/pyfits/column.py", line 1862, in _get_index
    raise KeyError("Key '%s' does not exist." % key)
KeyError: "Key 'LAMBDA' does not exist."

Do you know how to correct this ?
Thank you for your help,

Aureliver

**Comment by boada** [comment]
Hey @Aureliver. The `spDR-0*.fit` files are the templates and aren't really meant to be run through the machinery. Try downloading a spectrum from the SDSS. 

That won't immediately work either, because the finder is looking for a field called `lambda` -- the corresponding wavelengths. The SDSS spectrum files don't have that either. They do have a `loglam` or log lambda field. So that's a start. 

I'm still pretty sure the spectrum would need to be modified to be in the IRAF format, but that should give you something that will at least be pointing in the right direction. I'll try to have a look at things later tonight/tomorrow and see if we can't work it out.
